### ISSUE TITLE
TLS Client Hello: Legacy_Compression_Methods_Length wrong value constraint

### ISSUE THREAD

**Issue by rssen** [Componolit/RecordFlux-specifications#103]
The field value of `TLS Client Hello: Legacy_Compression_Methods_Length` is contraint to `1..1` but should allow values `1..2^8-1` (see RFC [5246](https://datatracker.ietf.org/doc/html/rfc5246#section-7.4.1.2)).

This occured while parsing the sample `tests/data/tls_handshake/handshake/valid/client_hello_0_header_removed.raw` which is currently on the issue_10 branch.

```
pyrflx: error: Error while parsing nested message TLS_Handshake::Client_Hello
pyrflx: error: cannot set value for field Legacy_Compression_Methods_Length
pyrflx: error: value 2 not in type range 1 .. 1
```

When changing this in the specification and repeating the parsing test (with compression length = 2), the outgoing conditions of `Legacy_Compression_Methods` fail.

```
AssertionError: unresolved field conditions in Client_Hello.Legacy_Compression_Methods: 1255 / 8 /= 351 / 8, 1255 / 8 = 351 / 8`
```

**Comment by treiher** [comment]
Our TLS specification only targets TLS 1.3 (RFC 8446). We do not intend to support previous TLS versions. This is unfortunately not documented. We should change that and add a comment to the specification files.

**Comment by treiher** [comment]
I have created a PR (#106) to document that only TLS 1.3 is supported.
