### ISSUE TITLE
HTTP/2

### ISSUE THREAD

**Issue by treiher** [Componolit/RecordFlux-specifications#3]
- [x] Gather valid real-world messages of HTTP/2
- [x] Derive set of invalid messages (by manual invalidation)
- [x] Add test data to `test/data`

### Resources

[RFC7540](https://tools.ietf.org/html/rfc7540)
[Tools for debugging, testing and using HTTP/2](https://blog.cloudflare.com/tools-for-debugging-testing-and-using-http-2/)

**Comment by rssen** [comment]
Due to https://github.com/Componolit/RecordFlux/issues/555 the HTTP/2 spec has to be changed.
```
Payload_Length : Payload_Length
    then Frame_Type
       if Message'Size = (Payload_Length + 9) * 8;
```
`Message'Size` is not on a link to final.

**Comment by senier** [comment]
> Due to [Componolit/RecordFlux#555](https://github.com/Componolit/RecordFlux/issues/555) the HTTP/2 spec has to be changed.
> 
> ```
> Payload_Length : Payload_Length
>     then Frame_Type
>        if Message'Size = (Payload_Length + 9) * 8;
> ```
> 
> `Message'Size` is not on a link to final.

While we're at it: Can you explain the literal 9 in the spec? Is there a different way to express it in terms of fields?

**Comment by rssen** [comment]
The HTTP/2 header has a fixed length of 9 bytes. The constant is used because of https://github.com/Componolit/RecordFlux/issues/517

**Comment by senier** [comment]
> The HTTP/2 header has a fixed length of 9 bytes. The constant is used because of [Componolit/RecordFlux#517](https://github.com/Componolit/RecordFlux/issues/517)

Am I right that this will become a non-issue once you move the constraint towards the final edges and that an expression can be used instead of the literal?

**Comment by rssen** [comment]
Yes, we would need to add the Message'Size condition to every edge towards the final node (which is what we were originally trying to circumvent)

**Comment by senier** [comment]
> Yes, we would need to add the Message'Size condition to every edge towards the final node (which is what we were originally trying to circumvent).

This will be improved in Componolit/RecordFlux#554

**Comment by rssen** [comment]
II ran the validation tool for the HTTP/2 Spec. Things that were found and need to be changed so far:
(checked means already fixed)

- [X] Header-Flags are in reverse order
- [X] A `Settings` Frame has to have a length of a multiple of 6, not exactly 6 bytes
- [ ] Something is not working with the Settings-Parameter (needs more debugging)


Out of 73 frames that should be valid,4 frames are classified incorrectly and those are `Settings-Frames` with `Settings-Parameters`
