### ISSUE TITLE
Integrate validation tool into RecordFlux

### ISSUE THREAD

**Issue by senier** [Componolit/RecordFlux-specifications#32]
The validation tool (especially once we have coverage analysis) should become a subcommand of `rflx`.

**Comment by treiher** [comment]
Wouldn't this issue fit better into the RecordFlux repository? We need at least another issue in RecordFlux to plan the time of its integration.

**Comment by senier** [comment]
Fair enough. Closing in favor of Componolit/RecordFlux#560
