### ISSUE TITLE
Support checksums in validation tool

### ISSUE THREAD

**Issue by senier** [Componolit/RecordFlux-specifications#45]
Specifications which have a checksum attached, currently raise an exception (even on correct input data):

```Console
$ ./tools/validate_spec.py -s igmp.rflx -m IGMP::Message -v tests/data/igmp/valid/
Traceback (most recent call last):
  File "./tools/validate_spec.py", line 334, in <module>
    sys.exit(cli(sys.argv))
  File "./tools/validate_spec.py", line 82, in cli
    validation_main(args)
  File "./tools/validate_spec.py", line 135, in validation_main
    validation_result = validator.validate_message(msg)
  File "./tools/validate_spec.py", line 206, in validate_message
    parsed_message.bytestring == original_message.bytes
  File "/home/senier/.local/lib/python3.7/site-packages/rflx/pyrflx/typevalue.py", line 1046, in bytestring
    if not self._skip_verification and not self.valid_message:
  File "/home/senier/.local/lib/python3.7/site-packages/rflx/pyrflx/typevalue.py", line 1103, in valid_message
    for checksum in self._checksums.values()
  File "/home/senier/.local/lib/python3.7/site-packages/rflx/pyrflx/typevalue.py", line 1103, in <genexpr>
    for checksum in self._checksums.values()
  File "/home/senier/.local/lib/python3.7/site-packages/rflx/pyrflx/typevalue.py", line 981, in _calculate_checksum
    f"cannot calculate checksum for {checksum.field_name}: "
rflx.pyrflx.error.PyRFLXError: pyrflx: error: cannot calculate checksum for Checksum: no callable checksum function provided
```

We currently have no way to provide a checksum function to the validation tool.

The following needs to be done additionally as part of this ticket:

- [ ] Fix checksum in TCP specification (cf. #63).

**Comment by rssen** [comment]
To achieve that, the user must be able to provide a checksum function (or multiple thereof) in a separate module.
Would it be ok if the user would be required to implement a module with the following contents:
```python3
def checksum_function() -> int:
   # implement checksum functionality
   pass

def checksum_function_2() -> int:
   # implement checksum functionality
   pass

checksum_functions: Dict[str, Callable] = {"Name_Checksum_Field_1": checksum_function, "Name_Checksum_Field_2": checksum_function_2}
```
?
This module can then be dynamically imported in the validation tool and the `checksum_function` dict can be passed as is to `message_value.set_checksum_functions`. This method requires a dict that maps the checksum field name to the checksum function.

I currently don`t see a better solution as the tool should be operated from the cli, where obviously no python dicts or functions can be passed. Instead, the user would be required to specify the module name.

**Comment by treiher** [comment]
The suggested approach sounds reasonable to me. I think it could be useful to allow checksum definitions for multiples message in one module:

```Python
checksum_functions = {
    "Package1::Message1": {"Field1": checksum_function_1, "Field2": checksum_function_2},
    "Package2::Message1": {"Field2": checksum_function_3, "Field4": checksum_function_4},
}
```
