### ISSUE TITLE
Tool for extracting packet bytes from PCAP file

### ISSUE THREAD

**Issue by treiher** [Componolit/RecordFlux-specifications#56]
The tool should be able to extract all packets of a specified protocol layer from a PCAP file and write the byte representation of each packet into a separate file.

**Comment by urbasus** [comment]
On a related note PCAP support for protocol test files would be an improvement compared to checking raw packet binaries into the repository. Would allow for using much more competent tooling when working with the files.

Ping me once this issue is closed and (maybe) I'll look into it.

**Comment by senier** [comment]
> On a related note PCAP support for protocol test files would be an improvement compared to checking raw packet binaries into the repository. Would allow for using much more competent tooling when working with the files.

Using PCAP directly could be helpful, indeed. Raw binaries have the benefit, though, that you can easily check whether they make sense using a hex editor. PCAP introduces another potential source of errors.

Out of curiosity: What would be the tooling you have in mind? E.g. I often have the situation that I want to extract packets of a certain protocol type and strip away upper-layer protocol headers (e.g. only extract the DHCP packet bytes from an Ethernet capture).

**Comment by urbasus** [comment]
> > On a related note PCAP support for protocol test files would be an improvement compared to checking raw packet binaries into the repository. Would allow for using much more competent tooling when working with the files.
> 
> Using PCAP directly could be helpful, indeed. Raw binaries have the benefit, though, that you can easily check whether they make sense using a hex editor. PCAP introduces another potential source of errors.
> 
> Out of curiosity: What would be the tooling you have in mind? E.g. I often have the situation that I want to extract packets of a certain protocol type and strip away upper-layer protocol headers (e.g. only extract the DHCP packet bytes from an Ethernet capture).

Wireshark can import and export PCAP. This is what is look like browsing a message I just captured, but importing a PCAP message should be just as easy:

![image](https://user-images.githubusercontent.com/25083765/111386734-f81bcb00-86ac-11eb-9c38-e9f3a4d72560.png)

You can select can export sections as binary.

![image](https://user-images.githubusercontent.com/25083765/111387062-6fe9f580-86ad-11eb-88fc-ad4fb3f9f3c1.png)

I do not know how to import binary back into Wireshark. Hence the push for PCAP.

**Comment by senier** [comment]
> I do not know how to import binary back into Wireshark. Hence the push for PCAP.

Wireshark is nice for working with packets interactively. The Export Packet Bytes feature is cumbersome if you want to export dozens or hundreds of packets. That's why we created this tool in the first place. I was wondering whether some PCAP-based tool for such bulk export exists (maybe some `tshark` or `tcpdump` magic, but I'm not sure).

Btw, you can import raw binaries using the Import from Hex Dump feature of Wireshark:

```
$ od -Ax -tx1 -v tests/data/arp/packet_ipv4/valid/arp_ipv4_reply.dat > arp_ipv4_reply.hex
```

`File` > `Import from Hex Dump`, select `arp_ipv4_reply.hex` and chose `Ethernet` with an ether type of `0806` (ARP). Admittedly, not very convenient ;)
