### ISSUE TITLE
Tool for generating specification from IANA document

### ISSUE THREAD

**Issue by treiher** [Componolit/RecordFlux-specifications#58]
IANA provides XML documents listing assigned numbers. Currently, we have a tool which generates a specification from the IANA Assigned Internet [Protocol Numbers](https://www.iana.org/assignments/protocol-numbers/protocol-numbers.xml) document. The tool could be made more generic and also used for other documents, e.g., [TLS Parameters](https://www.iana.org/assignments/tls-parameters/tls-parameters.xml).

### Naming of specification files

`<registry xmlns="http://www.iana.org/assignments" id="bootp-dhcp-parameters">` -> `Bootp_Dhcp_Parameters.rflx`

**Comment by treiher** [comment]
Further use cases would be the [Operation Codes](https://www.iana.org/assignments/arp-parameters/arp-parameters.xml#arp-parameters-1) of ARP and the [Hardware Types](https://www.iana.org/assignments/arp-parameters/arp-parameters.xml#arp-parameters-2) of DHCP.

**Comment by treiher** [comment]
And the [Dynamic Host Configuration Protocol (DHCP) and Bootstrap Protocol (BOOTP) Parameters](https://www.iana.org/assignments/bootp-dhcp-parameters/bootp-dhcp-parameters.xml).

**Comment by rssen** [comment]
I have some questions regarding the implementation of the IANA tool:

Which XML library?
 - do we trust the XML data from iana.org?
 - defusedxml -> Patches for stdlib xml modules (recommended in the python docs if an application parses xml from untrusted sources)

Does it have to be XML? 
 - CSV also available
 - Pro CSV: no clutter text just the table content 
 - Con: download all csv files separatly instead of one XML document

Additional Information?
- What should happen to additional information 
  contained in the table? e. g. Data Length - 
  column in DHCP Options
- Include the additional info in a comment?

Unassigned/Reserved Values (e.g. TLS GREASE)?
 - The names of those parameters are not unique 

Decimal / Hex Values?
- sometimes Hex-Values are used (even with a comma seperation) -> TLS Cipher Suites
- sometimes decimal values are used -> convert those?

Ranges
- If Ranges of values are used -> for each element of that range one rflx value? 
- e.g. TLS Authorization Data Formats

Which Notes/Comments from the XML file should be included?

**Comment by treiher** [comment]
To summarize the results of our separate discussion:

> Which XML library?

If there are no disadvantages, the more secure `defusedxml` should be used.

> Does it have to be XML?

Yes, otherwise we would loose the additional information contained in the XML file.

> Additional Information?

The additional information should be added as comments.

> Unassigned/Reserved Values (e.g. TLS GREASE)?

Parameters with non-unique names can be made unique by appending the respective value to their names.

Unassigned values can be ignored.

> Decimal/Hex Values?

The same representation system should be used in the generated specification as in the IANA document. This should make it easier match values in the generated specification with ones in a RFC.

> Ranges

Should be only relevant for unassigned values, which will be ignored.

> Which notes/comments from the XML file should be included?

In doubt preserving more information as comments should be preferred.

**Comment by treiher** [comment]
It would be useful to have an option to add `Always_Valid` to all types. In case of TLS 1.3 this is the default and IMHO it makes sense to also allow setting this default in the tool:

```
3.5.  Enumerateds

[...]

   Future extensions or additions to the protocol may define new values.
   Implementations need to be able to parse and ignore unknown values
   unless the definition of the field states otherwise.
```

https://tools.ietf.org/html/rfc8446#section-3.5

**Comment by rssen** [comment]
I noticed that the "BOOTP Vendor Extensions and DHCP Options" registry in https://www.iana.org/assignments/bootp-dhcp-parameters/bootp-dhcp-parameters.xml contains duplicate values (not identifiers) e.g. the value 150 is assigned to 3 identifiers and the value 128 to 6 identifiers. How should this be resolved?  

![grafik](https://user-images.githubusercontent.com/61687542/119796101-5fd66980-bed9-11eb-94fd-b813964188b9.png)

**Comment by rssen** [comment]
Is there a comprehensive list of all reserved words (that cannot be used as identifiers) somewhere? 
My list so far is: `["end", "is", "id", "package", "type", "with"]`.

 Are `Size` and `Always_Valid` reserved words? When `Size` is used I get  `model: error: conflicting literals: SIZE` and  `model: info: previous occurrence of "SIZE"` although Size is not used as an identifier in this particular type before.

**Comment by treiher** [comment]
> Is there a comprehensive list of all reserved words (that cannot be used as identifiers) somewhere?
> My list so far is: `["end", "is", "id", "package", "type", "with"]`.

You can find a list of all reserved words here: https://github.com/Componolit/RecordFlux/blob/main/rflx/specification/const.py.

> Are `Size` and `Always_Valid` reserved words?

No, `Size` and `Always_Valid` are not reserved words, but their use could still have unanticipated effects. If there are issues with identifiers which are not reserved words, please create an issue with a small reproducer.

>  When `Size` is used I get `model: error: conflicting literals: SIZE` and `model: info: previous occurrence of "SIZE"` although Size is not used as an identifier in this particular type before.

I cannot reproduce that. These error messages should point to the conflicting lines in the specification, so you should see where `Size` was used before. If that is not the case, this would also be a bug.

**Comment by rssen** [comment]
> I noticed that the "BOOTP Vendor Extensions and DHCP Options" registry in https://www.iana.org/assignments/bootp-dhcp-parameters/bootp-dhcp-parameters.xml contains duplicate values (not identifiers) e.g. the value 150 is assigned to 3 identifiers and the value 128 to 6 identifiers. How should this be resolved?

I`ll just join the names for now and create one overly long identifier.

**Comment by treiher** [comment]
> > I noticed that the "BOOTP Vendor Extensions and DHCP Options" registry in https://www.iana.org/assignments/bootp-dhcp-parameters/bootp-dhcp-parameters.xml contains duplicate values (not identifiers) e.g. the value 150 is assigned to 3 identifiers and the value 128 to 6 identifiers. How should this be resolved?
> 
> I`ll just join the names for now and create one overly long identifier.

Another option would be to use some heuristic to choose just one of the identifiers. The other identifiers could still be mentioned in a comment.

**Comment by treiher** [comment]
> @treiher can you please check if the general format of the generated specification file is correct? It should work with any of the registries in this issue.

A few things I noticed:

- There is a missing line break in the header comment.
- All identifiers should use `Mixed_Case_With_Underscores` (cf. Componolit/RecordFlux#1218).
- The literals should be aligned behind the opening parenthesis (i.e. the literals are currently under-indented by one space).

I think we should add the generated specification files to the repository. This simplifies the review process and subsequently allows reading and using the specifications without any additional preprocessing steps.

> I know that `Size` is not a multiple of 8 in every case ATM, that will be fixed.

That is not necessarily the case, e.g., the [Datum Registry](https://datatracker.ietf.org/doc/html/rfc6225#section-4.3) (a part of a DHCP option) has a size of 3 bit.
